name = "DiscreteNaturalNeighbors"
uuid = "43764a4e-051a-43e5-af11-231f204a2450"
authors = ["Benjamin Hertzsch <benjamin.hertzsch@ed.ac.uk> and contributors"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
LinearAlgebra = "1.11.0"
NearestNeighbors = "0.4.22"
ProgressMeter = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
